name: gateline_errors
description: A Flutter app which displays information about UK railway ticket barrier errors.

publish_to: "none"

version: 1.0.2+2

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_admob: ^0.9.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.5

flutter_icons:
  android: true
  ios: true
  image_path_android: assets/icon/ic_launcher_xxxhdpi.png
  image_path_ios: assets/icon/icon.png
  adaptive_icon_background: assets/icon/ic_background.png
  adaptive_icon_foreground: assets/icon/ic_foreground.png

flutter:
  uses-material-design: true

  fonts:
    - family: VT323
      fonts:
        - asset: fonts/VT323-Regular.ttf
